version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "clap_derive"
      - dependency-name: "futures-channel"
      - dependency-name: "futures-core"
      - dependency-name: "futures-io"
      - dependency-name: "futures-sink"
      - dependency-name: "futures-task"
      - dependency-name: "futures-util"
      - dependency-name: "tracing-core"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
