name: Check

on:
  pull_request: {}

jobs:
  check:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v47-rust
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: git config --global --add safe.directory "$PWD" # actions/runner#2033
      - run: just fetch
      - run: just check-fmt
      - run: just clippy
      - run: just doc
      - run: just test-build
      - run: just test

  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    # Prevent sudden announcement of a new advisory from failing Ci.
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25
        with:
          command: check ${{ matrix.checks }}
